DROP SCHEMA IF exists fog_db;
Create schema fog_db;
Use fog_db;


CREATE TABLE IF NOT EXISTS `fog_db`.`bruger` (
  `brugerId` INT(11) NOT NULL AUTO_INCREMENT,
  `navn` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `rolle` VARCHAR(45) NULL DEFAULT NULL,
  `adresse` VARCHAR(45) NULL DEFAULT NULL,
  `postnr` INT(11) NULL DEFAULT NULL,
  `telefon` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`brugerId`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `fog_db`.`ordre` (
  `ordreAntal` INT(11) NOT NULL AUTO_INCREMENT,
  `vareNr` INT(11) NULL DEFAULT NULL,
  `ordreNr` INT(11) NULL DEFAULT NULL,
  `kundeId` INT(11) NULL DEFAULT NULL,
  `dato` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ordreAntal`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `fog_db`.`tagtyper` (
  `tagtypeNr` INT(11) NOT NULL AUTO_INCREMENT,
  `tagtypeNavn` VARCHAR(45) NULL DEFAULT NULL,
  `dækningsGrad` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`tagtypeNr`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `fog_db`.`varedetaljer` (
  `vareNr` INT(11) NOT NULL,
  `højde` DOUBLE NULL DEFAULT NULL,
  `længde` DOUBLE NULL DEFAULT NULL,
  `bredde` DOUBLE NULL DEFAULT NULL,
  `vægt` DOUBLE NULL DEFAULT NULL,
  `hældning` DOUBLE NULL DEFAULT NULL,
  `farve` VARCHAR(45) NULL DEFAULT NULL,
  `materiale` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`vareNr`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `fog_db`.`varer` (
  `vareNr` INT(11) NOT NULL AUTO_INCREMENT,
  `vareNavn` VARCHAR(45) NULL DEFAULT NULL,
  `antal` INT(11) NULL DEFAULT NULL,
  `pris` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`vareNr`))
ENGINE = InnoDB;